// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kmuxaderwhvquajiynto.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImttdXhhZGVyd2h2cXVhaml5bnRvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxNzc5MzksImV4cCI6MjA2MDc1MzkzOX0.Th6Ec1d7tflJRYTg_sKVU1HbZjF1GEf4MGactmSlvKc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);